Add wp cli support
woocommerce/bookings-helper pull request #33
Opened 2023-02-27 11:38 UTC by ravinderk

#32

2023-02-27 16:34 UTC, faisal-alvi commented
@ravinderk is this ready for review? Seems like you are fixing `phpcs` errors.

2023-02-27 16:56 UTC, ravinderk commented
> @ravinderk, is this ready for review? It seems like you are fixing `phpcs` errors.

@faisal-alvi PHPCS issues have been fixed. I left a few errors intentionally, so we remember to resolve them.

2023-03-01 16:27 UTC, faisal-alvi requested changes
@ravinderk thank you for the PR. I have left some feedback, can you please check?

1. The exported file is always named in the format `booking-product-YYYY-MM-DD.zip`, which can lead to overwriting of the previous file. To avoid this, I recommend adding a timestamp or some other unique key to the file name.
2. I believe that replacing `x.x.x` with `1.0.6` in all function documentation would be acceptable.
3. Please add information to the README file on how to use WP CLI for importing and exporting, along with various examples. Additionally, include a table that shows all parameters and their details.
4. According to the UI, we can import a product and select a checkbox if we also need to import the global rules. Can we add a new parameter in WP CLI to perform the same function as the checkbox? So when the parameter is found, we would also import the global rules along with the product.

![image](https://user-images.githubusercontent.com/25176325/222201147-5a3acbdf-eef2-4abf-89e4-36a740122867.png)

5. When trying to import the product using the user interface, a warning is thrown:

```jsx
( ! ) Warning: Undefined array key "product" in /Users/faisalalvi/LocalSites/wpne/app/public/wp-content/plugins/bookings-helper/includes/class-wc-bookings-helper-import.php on line 264
Call Stack
#	Time	Memory	Function	Location
1	16769061803.9464	376600	{main}( )	.../tools.php:0
2	16769061803.9464	377880	require_once( '/Users/faisalalvi/LocalSites/wpne/app/public/wp-admin/admin.php )	.../tools.php:40
3	16769061803.9464	378712	require_once( '/Users/faisalalvi/LocalSites/wpne/app/public/wp-load.php )	.../admin.php:34
4	16769061803.9464	379344	require_once( '/Users/faisalalvi/LocalSites/wpne/app/public/wp-config.php )	.../wp-load.php:50
5	16769061803.9464	388648	require_once( '/Users/faisalalvi/LocalSites/wpne/app/public/wp-settings.php )	.../wp-config.php:115
6	16769061803.9464	13869328	do_action( )	.../wp-settings.php:617
7	16769061803.9464	13869704	WP_Hook->do_action( )	.../plugin.php:517
8	16769061803.9464	13869704	WP_Hook->apply_filters( )	.../class-wp-hook.php:332
9	16769061803.9464	15659320	WC_Bookings_Helper_Import->catch_import_requests( )	.../class-wp-hook.php:308
10	16769061803.9464	15659360	WC_Bookings_Helper_Import->import_product( )	.../class-wc-bookings-helper-import.php:60
11	16769061803.9464	15671456	WC_Bookings_Helper_Import->import_product_from_json( )
```

2023-03-01 18:40 UTC, ravinderk commented
@faisal-alvi 
1. Done
2. Done
3. Done
4. I did not find the logic that includes global availability rules in exported JSON data.  I am not whether this option works as intended.
5.  You are getting error because I did not add support to import `wp cli` generated zip file from the user interface. But I can see that this will happen occasionally, so I implement support.

2023-03-02 10:16 UTC, faisal-alvi commented
@ravinderk as per our discussion, you will work on importing global rules along with the product zip in CLI. Please ping me once this is ready for review.

2023-03-02 15:52 UTC, ravinderk commented
@faisal-alvi pull request is ready to review.

2023-03-03 14:16 UTC, faisal-alvi requested changes
@ravinderk Thank you for the changes. I have reviewed the changes and tested them thoroughly. However, I found that some of the tests are failing. Please check the following test results:

* Tested and vice versa functionalities for exporting and importing products, including different combinations of rules, resources, and files. Please see the below table for the detailed results.
* Checked the code for version compatibility, formatting, and naming conventions.
* I found that the `/wp-cli-commands/class-wc-bookings-helper-products-command.php` file contains wrong examples in the function doc, and the readme file does not have the correct names of the WP CLI command, i.e., `booking-helper` instead of `bookings-helper` and `import-product` instead of `import-products`. Please update the files accordingly.
* Checked all the CLI and commands mentioned in the readme. I ran multiple CLI commands with different parameters and options to test their functionality.
* Checked if the old zip file `OLD-booking-product-9379-2023-02-08.zip` works in UI and CLI. It works in UI but not in CLI. ([OLD-booking-product-9379-2023-02-08.zip](https://github.com/woocommerce/bookings-helper/files/10882187/OLD-booking-product-9379-2023-02-08.zip))
* The multiple products can not be exported in UI. I suggested creating an issue ticket for that. (This was not the part of work in this PR so we can handle it later in another PR)
* The `phpcs` checks are failing but ignored in testing as you mentioned those are intentionally ignored.
* Suggested changing the `export-availability-rules` to `export-global-availability-rules` and changing the `import-availability-rules` to `import-global-availability-rules` so it is more apparent that we are mentioning the global rules not the product/resource level rules.
* It is noted that the special characters are added as a unique post-fix in the exported file from CLI (`booking-products-2023-03-03-%)P&5.zip`, containing "%" and "&" chars). We should only use alphanumeric key. 
* Also it makes an issue when importing with such file name, it does not import and shows ">".

![image](https://user-images.githubusercontent.com/25176325/222707334-4ee7cfbd-bc4d-4cba-b76a-df3c6d2c3eef.png)

![image](https://user-images.githubusercontent.com/25176325/222708453-705eeae1-e73a-4ce9-be1a-025b3418ebd6.png)

* When trying to import a single product zip in the CLI, that was exported using CLI, it throws the Fatal error and fails.

![image](https://user-images.githubusercontent.com/25176325/222708898-3eae0189-9dae-4e04-b6c3-f199d9c1e7f0.png)

---

### Here is the test result table:

<table><thead><tr><th>Test</th><th>Result</th></tr></thead><tbody><tr><td>Single Product Export UI → Import UI</td><td>✅</td></tr><tr><td>Single Product Export UI → Import CLI (PHP fatal)</td><td>❌</td></tr><tr><td>Single Product Export CLI → Import CLI (PHP fatal)</td><td>❌</td></tr><tr><td>Single Product Export CLI → Import UI</td><td>✅</td></tr><tr><td>Single Product + Rules Export UI → Import UI (the product imported successfully but the global Rules are not imported even the the checkbox was ticked)</td><td>❌</td></tr><tr><td>Single Product + Rules Export UI → Import CLI</td><td>✅</td></tr><tr><td>Single Product + Rules Export CLI → Import CLI</td><td>❌</td></tr><tr><td>Single Product + Rules Export CLI → Import UI</td><td>✅</td></tr><tr><td>Multiple Products Export UI → Import UI (not supported yet)</td><td>⚠️</td></tr><tr><td>Multiple Products Export UI → Import CLI (not supported yet)</td><td>⚠️</td></tr><tr><td>Multiple Products Export CLI → Import CLI</td><td>❌</td></tr><tr><td>Multiple Products Export CLI → Import UI</td><td>✅</td></tr><tr><td>Multiple Products + Rules Export UI → Import UI (not supported yet)</td><td>⚠️</td></tr><tr><td>Multiple Products + Rules Export UI → Import CLI (not supported yet)</td><td>⚠️</td></tr><tr><td>Multiple Products + Rules Export CLI → Import CLI</td><td>❌</td></tr><tr><td>Multiple Products + Rules Export CLI → Import UI</td><td>✅</td></tr></tbody></table>

Please let me know if you have any questions or concerns about the above findings.

2023-03-03 14:24 UTC, ravinderk commented on README.md
> +
@faisal-alvi It is not an extra line. Each heading in the readme has one newline above and below.

2023-03-03 14:33 UTC, ravinderk commented on includes/class-wc-bookings-helper-export.php
> -			}
@faisal-alvi This code still exists in `WC_Bookings_Helper_Export::get_global_availability_rules`

2023-03-03 15:32 UTC, ravinderk commented
@faisal-alvi Issue you reported has been fix. Let discuss it before you start testing.

2023-03-07 11:25 UTC, faisal-alvi requested changes

2023-03-07 11:25 UTC, faisal-alvi commented on includes/wp-cli-commands/class-wc-bookings-helper-global-availability-rules-command.php
> +	 * wp bookings-helper-availability-rules export --dir=/path/to/export
```suggestion
	 * wp bookings-helper export-global-availability-rules
	 * wp bookings-helper export-global-availability-rules --dir=/path/to/export
```

2023-03-07 11:25 UTC, faisal-alvi commented on includes/wp-cli-commands/class-wc-bookings-helper-global-availability-rules-command.php
> +	 * wp bookings-helper-availability-rules import --file=/path/to/absolute_path_to_zip_file
```suggestion
	 * wp bookings-helper import-global-availability-rules --file=/path/to/absolute_path_to_zip_file
```

2023-03-07 11:25 UTC, faisal-alvi commented on includes/wp-cli-commands/class-wc-bookings-helper-products-command.php
> +	 * wp bookings-helper-products export --all --with-global-availability-rules
```suggestion
	 * wp bookings-helper export-global-availability-rules --all
	 * wp bookings-helper export-global-availability-rules --all --dir=/path/to/export
	 * wp bookings-helper export-global-availability-rules --products="68,73"
	 * wp bookings-helper export-global-availability-rules --all --with-global-availability-rules
```

2023-03-07 11:25 UTC, faisal-alvi commented on includes/wp-cli-commands/class-wc-bookings-helper-products-command.php
> +	 * wp bookings-helper-products import --all --file=/path/to/absolute_path_to_zip_file
```suggestion
	 * wp bookings-helper import-global-availability-rules --all --file=/path/to/absolute_path_to_zip_file
```

2023-03-07 11:28 UTC, faisal-alvi commented on includes/wp-cli-commands/class-wc-bookings-helper-products-command.php
> +	 * wp bookings-helper export-global-availability-rules --all --with-global-availability-rules
```suggestion
	 * wp bookings-helper export-products --all
	 * wp bookings-helper export-products --all --dir=/path/to/export
	 * wp bookings-helper export-products --products="68,73"
	 * wp bookings-helper export-products --all --with-global-availability-rules
```

2023-03-07 11:38 UTC, faisal-alvi approved these changes
@ravinderk thank you for your hard work on this pull request. I tested it and everything looks good to me!

2023-03-07 11:39 UTC, faisal-alvi commented
@dkotter should we move it to UAT or direct merge it?

2023-03-07 22:02 UTC, dkotter commented
@faisal-alvi This can be in UAT for now and Jeff and I will review in our next UAT session.

2023-03-13 16:23 UTC, jeffpaul approved these changes
Looks good to me, @dkotter if you're 👍🏼 then feel free to move along

2023-03-15 12:00 UTC, merged